version: "3.1"

services:
  postgressrv:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "nlw-pass-in"
    ports:
      - 5440:5432
    volumes:
      - ~/.postgres/nlw-pass-in/data:/var/lib/postgresql/data
